### ISSUE TITLE
Cant install UwUntuCC

### ISSUE THREAD

**Issue by Tauro101** [sall0-0p/UwUntuCC#21]
**Describe the bug**
This doesnt let me install UwUntuCC
**To Reproduce**
1. I copyed github link
2. opended cmd
3. cloned the git repo
4. draged startup ,OS folder and APPS folder in the root of computer
5. strg r restarted
6. error basalt not found
**Expected behavior**
It to start but it didnt work
**Screenshots**
![BUG](https://user-images.githubusercontent.com/115424904/204819456-4c01ce16-7964-42a4-a273-f5ca372ce74f.png)
after restart

**Additional context**

**Version**
Where do you launch UwU? On craftOS PC? CC Tweaked? Please state here.
Computercraft 1.80pr1 (CCemuX 1.0.0) = _G._HOST

**Comment by sall0-0p** [comment]
Hello, sorry for not noticing your issue for few days. I recommend you trying to launch dev build. It could be more stable. But still all this is still WIP, there are lots of options in development and debug there.

**Comment by Tauro101** [comment]
ok
