### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by Apethesis** [sall0-0p/UwUntuCC#24]
Considering LevelOS is the windows clone, rename UwUntuCC to prestigeOS (or just Prestige).
I imagine the logo would look like the image below.
![prestigeOS](https://user-images.githubusercontent.com/86126617/206549717-3e888fbd-1a72-4abd-bf18-e4fcf7a4494b.png)

**Comment by sall0-0p** [comment]
No, I want to rename it. But prestigeOS is not the name Im looking for =(

**Comment by Apethesis** [comment]
hmm
why not prestigeOS
also any other ideas then

**Comment by sall0-0p** [comment]
I feel okay about UwUntuCC. prestigeOS feels a bit cringe.

**Comment by sall0-0p** [comment]
Also you can post such things in discord #suggestions

**Comment by Apethesis** [comment]
i dunno man ask the others in the discord
and UwUntuCC seems more cringe than prestigeOS
